import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BackgroundWrapper from "@/components/BackgroundWrapper";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
  icon: [
    { url: "../favicomatic/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    { url: "../favicomatic/favicon-32x32.png", sizes: "32x32", type: "image/png" },
  ],
  shortcut: [{ url: "../favicomatic/favicon.ico" }],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <BackgroundWrapper>
          <Navbar />
          {children}
          <Footer />
        </BackgroundWrapper>
      </body>
    </html>
  );
}
